# Generated by Django 2.0.5 on 2018-07-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='image',
        ),
    ]
