# Generated by Django 2.0.5 on 2018-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='email_emp',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='email_resp',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
