# Generated by Django 2.0.5 on 2018-07-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_docs_integracao_email_resp'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloq_hse',
            fields=[
                ('fun', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='cadastro.funcionario')),
                ('motivo', models.CharField(max_length=1000)),
                ('data_bloq', models.DateField(auto_now=True)),
            ],
        ),
    ]
