# Generated by Django 2.0.5 on 2018-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hse', '0006_aux_table_email_resp_cham'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_hse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
