# Generated by Django 2.0.5 on 2018-07-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hse', '0007_email_hse'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias_integracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seg', models.BooleanField(default=True)),
                ('Ter', models.BooleanField(default=True)),
                ('Qua', models.BooleanField(default=True)),
                ('Qui', models.BooleanField(default=True)),
                ('Sex', models.BooleanField(default=True)),
                ('Sab', models.BooleanField(default=True)),
                ('Dom', models.BooleanField(default=True)),
            ],
        ),
    ]
