# Generated by Django 2.0.5 on 2018-07-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hse', '0008_dias_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias_integracao',
            name='Dom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Qua',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Qui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Sab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Seg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Ter',
            field=models.BooleanField(default=False),
        ),
    ]
