# Generated by Django 2.0.5 on 2018-07-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hse', '0009_auto_20180723_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias_integracao',
            name='Dom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Qua',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Qui',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Sab',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Seg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Sex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Ter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
