# Generated by Django 2.0.5 on 2018-07-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hse', '0010_auto_20180724_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias_integracao',
            name='Dom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Qua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Qui',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Sab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Seg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dias_integracao',
            name='Ter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
